package world.urelion.partyvoicechat;

import de.maxhenkel.voicechat.api.BukkitVoicechatService;
import de.maxhenkel.voicechat.api.Player;
import de.maxhenkel.voicechat.api.VoicechatApi;
import de.maxhenkel.voicechat.api.VoicechatPlugin;
import de.maxhenkel.voicechat.api.events.Event;
import de.maxhenkel.voicechat.api.events.EventRegistration;
import de.maxhenkel.voicechat.api.events.MicrophonePacketEvent;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;
import lombok.Singleton;
import lombok.extern.slf4j.Slf4j;
import me.pikamug.unite.Unite;
import me.pikamug.unite.api.objects.PartyProvider;
import org.bukkit.Server;
import org.bukkit.plugin.PluginManager;
import org.bukkit.plugin.RegisteredServiceProvider;
import org.bukkit.plugin.ServicesManager;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import world.urelion.UrelionPlugin;

/**
 * main class of the {@link PartyVoiceChatPlugin},
 * which link all {@link Player}s of one party in Voice Chat
 *
 * @version 1.0.0
 * @since 1.0.0
 */
@Slf4j
@Singleton(style = Singleton.Style.HOLDER)
public class PartyVoiceChatPlugin
extends UrelionPlugin
implements VoicechatPlugin {
	/**
	 * {@link Singleton} instance of the {@link PartyVoiceChatPlugin}
	 *
	 * @since 1.0.0
	 */
	@SuppressFBWarnings(
		value = "MS_EXPOSE_REP",
		justification = "Getter is generated by Lombok."
	)
	@Getter
	@Setter(AccessLevel.PRIVATE)
	private static @Nullable PartyVoiceChatPlugin INSTANCE;

	/**
	 * {@link PartyProvider} to get party information by {@link Unite}
	 *
	 * @since 1.0.0
	 */
	@Getter
	private @Nullable PartyProvider partyProvider = null;

	/**
	 * @return the unique identifier of this {@link VoicechatPlugin}
	 *
	 * @since 1.0.0
	 */
	@Override
	public @NotNull String getPluginId() {
		PartyVoiceChatPlugin.log.trace("Get plugin name.");
		return this.getName();
	}

	/**
	 * called after this {@link VoicechatPlugin} was loaded
	 *
	 * @param voicechatApi the {@link VoicechatApi} to use Voice Chat
	 *
	 * @since 1.0.0
	 */
	@Override
	public void initialize(
		final @Nullable VoicechatApi voicechatApi
	) {
		PartyVoiceChatPlugin.log.trace("Check if the Voice Chat API is given.");
		if (voicechatApi == null) {
			PartyVoiceChatPlugin.log.error(
				"Voice Chat API not given! Cancel initializing."
			);
			return;
		}
	}

	/**
	 * register {@link Event}s
	 *
	 * @param eventRegistration the event registration object,
	 *                          used to register events
	 *
	 * @since 1.0.0
	 */
	@Override
	public void registerEvents(
		final @Nullable EventRegistration eventRegistration
	) {
		PartyVoiceChatPlugin.log.trace(
			"Check if the event registration is given."
		);
		if (eventRegistration == null) {
			PartyVoiceChatPlugin.log.error(
				"Event registration not given! Cancel initializing."
			);
			return;
		}

		eventRegistration.registerEvent(
			MicrophonePacketEvent.class,
			(new VoiceChatListener())::onMicrophone
		);
	}

	@Override public void whileLoad() {
		super.whileLoad();

		PartyVoiceChatPlugin.log.trace("Set plugin instance.");
		PartyVoiceChatPlugin.setINSTANCE(this);
	}

	/**
	 * enables the {@link PartyVoiceChatPlugin}
	 *
	 * @since 1.0.0
	 */
	@Override public void whileEnable() {
		super.whileEnable();

		PartyVoiceChatPlugin.log.trace("Get server.");
		final @NotNull Server server = this.getServer();
		PartyVoiceChatPlugin.log.trace("Get plugin manager.");
		final @NotNull PluginManager pluginManager = server.getPluginManager();
		PartyVoiceChatPlugin.log.trace("Get service manager.");
		final @NotNull ServicesManager servicesManager =
			server.getServicesManager();

		PartyVoiceChatPlugin.log.trace("Check if Unite plugin is loaded.");
		if (pluginManager.getPlugin("Unite") != null) {
			PartyVoiceChatPlugin.log.trace("Get registered service provider.");
			final @Nullable
			RegisteredServiceProvider<PartyProvider> registeredServiceProvider =
				servicesManager.getRegistration(PartyProvider.class);

			PartyVoiceChatPlugin.log.trace(
				"Check if party provider is registered."
			);
			if (registeredServiceProvider != null) {
				PartyVoiceChatPlugin.log.error("Get party provider.");
				this.partyProvider = registeredServiceProvider.getProvider();
			}
		}

		PartyVoiceChatPlugin.log.trace("Get Voice Chat service.");
		final @Nullable BukkitVoicechatService service =
			server.getServicesManager().load(
				BukkitVoicechatService.class
			);
		PartyVoiceChatPlugin.log.trace(
			"Check if Voice Chat service is loaded."
		);
		if (service != null) {
			PartyVoiceChatPlugin.log.trace("Register Party Voice Chat plugin.");
			service.registerPlugin(this);
		}
	}

	/**
	 * disables the {@link PartyVoiceChatPlugin}
	 *
	 * @since 1.0.0
	 */
	@Override public void whileDisable() {
		super.whileDisable();

		PartyVoiceChatPlugin.log.trace("Unregister Party Voice Chat plugin.");
		this.getServer().getServicesManager().unregister(this);
	}
}
